# -*- coding: utf-8 -*-
"""Aplicación de Análisis Energético Pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cc1L1t6TQC7XCM4pKZRRjG-u7T_8X8g
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import requests
import json
from datetime import datetime

# --- CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="IA Energy Consultant Pro",
    page_icon="⚡",
    layout="wide",
)

# --- ESTILOS PERSONALIZADOS ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 40px;
        border-radius: 15px;
        border: 1px solid #e2e8f0;
        box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        max-width: 1000px;
        margin: auto;
    }
    .stMetric {
        background-color: #f8fafc;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #e2e8f0;
    }
    .prompt-box {
        background-color: #f1f5f9;
        padding: 20px;
        border-left: 5px solid #1e40af;
        border-radius: 8px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 0.95em;
        margin-bottom: 25px;
        color: #1e293b;
        line-height: 1.5;
    }
    </style>
""", unsafe_allow_html=True)

# --- MAPEOS DE IDIOMA Y ORDEN ---
DIAS_ORDENADOS = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
MESES_ORDENADOS = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

DIAS_MAP = {'Monday': 'Lunes', 'Tuesday': 'Martes', 'Wednesday': 'Miércoles', 'Thursday': 'Jueves', 'Friday': 'Viernes', 'Saturday': 'Sábado', 'Sunday': 'Domingo'}
MESES_MAP = {'January': 'Enero', 'February': 'Febrero', 'March': 'Marzo', 'April': 'Abril', 'May': 'Mayo', 'June': 'Junio', 'July': 'Julio', 'August': 'Agosto', 'September': 'Septiembre', 'October': 'Octubre', 'November': 'Noviembre', 'December': 'Diciembre'}

@st.cache_data
def procesar_archivo(uploaded_file):
    try:
        if uploaded_file.name.endswith('.csv'):
            for encoding in ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']:
                try:
                    uploaded_file.seek(0)
                    df = pd.read_csv(uploaded_file, sep=None, engine='python', encoding=encoding)
                    break
                except UnicodeDecodeError: continue
        else:
            try: df = pd.read_excel(uploaded_file, sheet_name="TABLA HORARIA")
            except: df = pd.read_excel(uploaded_file)

        df.columns = df.columns.astype(str).str.strip()
        df = df.dropna(how='all', axis=0)
        cols_originales = list(df.columns)
        col_fecha_orig = next((c for c in cols_originales if c.lower() == 'fecha'), None)

        if col_fecha_orig:
            value_vars = [c for c in cols_originales if c.upper().startswith('H') and any(char.isdigit() for char in c)]
            if value_vars:
                df = df.melt(id_vars=[c for c in cols_originales if c not in value_vars], value_vars=value_vars, var_name='Hora_Raw', value_name='Energia_Melted')

            df.columns = [c.lower() for c in df.columns]
            terminos_busqueda = ['energia', 'kwh', 'consumo', 'valor', 'active', 'total']
            col_kwh = 'energia_melted' if 'energia_melted' in df.columns else next((c for term in terminos_busqueda for c in df.columns if term in c), None)

            if col_kwh:
                df = df.rename(columns={col_kwh: 'kwh', col_fecha_orig.lower(): 'fecha'})
                df['fecha_dt'] = pd.to_datetime(df['fecha'], errors='coerce')
                df['kwh'] = pd.to_numeric(df['kwh'], errors='coerce').fillna(0)
                df = df.dropna(subset=['fecha_dt'])

                if 'hora_raw' in df.columns:
                    df['hora_num'] = pd.to_numeric(df['hora_raw'].astype(str).str.extract('(\d+)')[0], errors='coerce').fillna(0).astype(int)
                else:
                    df['hora_num'] = df['fecha_dt'].dt.hour

                df['dia_nombre'] = df['fecha_dt'].dt.day_name().map(DIAS_MAP)
                df['mes_nombre'] = df['fecha_dt'].dt.month_name().map(MESES_MAP)

                # --- LÓGICA DE TARIFAS MEJORADA (RANGOS COMPLETOS) ---
                def categorizar_tarifa(h):
                    # Punta: 18:00 a 22:00 (Bloque de mayor costo)
                    if 18 <= h <= 21: return 'Alta (Punta)'
                    # Valle: 08:00 a 17:00 y 22:00 a 23:00 (Actividad comercial/industrial)
                    elif (8 <= h <= 17) or (h == 22) or (h == 23): return 'Media (Valle)'
                    # Super Valle: 00:00 a 07:00 (Madrugada)
                    else: return 'Baja (Super Valle)'

                df['tarifa'] = df['hora_num'].apply(categorizar_tarifa)
                precios = {'Alta (Punta)': 0.45, 'Media (Valle)': 0.25, 'Baja (Super Valle)': 0.15}
                df['costo_total'] = df['kwh'] * df['tarifa'].map(precios)
                return df
        return None
    except Exception as e:
        st.error(f"Error: {e}")
        return None

def gestionar_login():
    if "auth_state" not in st.session_state: st.session_state.auth_state = False
    if not st.session_state.auth_state:
        st.title("🔐 Acceso Energy BI")
        u, p = st.text_input("Usuario"), st.text_input("Contraseña", type="password")
        if st.button("Ingresar"):
            if u == "admin" and p == "admin123":
                st.session_state.auth_state, st.session_state.user_role, st.session_state.user_name = True, "Administrador", "Admin"
                st.rerun()
        return False
    return True

if gestionar_login():
    st.sidebar.title("Configuración")
    nombre_consultor = st.sidebar.text_input("Consultor", "Juan Pérez")
    cargo_consultor = st.sidebar.text_input("Cargo", "Especialista Energético")
    logo_file = st.sidebar.file_uploader("Logo Empresa", type=["png", "jpg"])

    if st.session_state.user_role == "Administrador":
        up_file = st.sidebar.file_uploader("Cargar Datos", type=["csv", "xlsx"])
        if up_file:
            data = procesar_archivo(up_file)
            if data is not None: st.session_state.df_master = data

    if "df_master" in st.session_state:
        df = st.session_state.df_master
        col_nombre = next((c for c in df.columns if 'nombre' in c or 'cliente' in c), None)
        clientes = ["Todos"] + sorted(list(df[col_nombre].unique())) if col_nombre else ["General"]
        cliente_sel = st.sidebar.selectbox("Filtrar por Cliente/Sede", clientes)
        df_view = df if cliente_sel in ["Todos", "General"] else df[df[col_nombre] == cliente_sel]

        t1, t2, t3, t4 = st.tabs(["📊 Análisis Principal", "🔬 Explorador Libre", "🧠 Sistema de Prompts", "📄 Informe Final"])

        with t1:
            st.subheader(f"Dashboard - {cliente_sel}")
            c1, c2 = st.columns(2)
            df_h = df_view.groupby('hora_num')['kwh'].mean().reset_index()
            fig_h = px.line(df_h, x='hora_num', y='kwh', title="Curva Horaria Promedio", markers=True)
            c1.plotly_chart(fig_h, use_container_width=True, key="main_h")

            df_d = df_view.groupby('dia_nombre')['kwh'].sum().reset_index()
            fig_d = px.bar(df_d, x='dia_nombre', y='kwh', title="Consumo por Día", category_orders={"dia_nombre": DIAS_ORDENADOS})
            c2.plotly_chart(fig_d, use_container_width=True, key="main_d")

            df_m = df_view.groupby('mes_nombre')['kwh'].sum().reset_index()
            fig_m = px.bar(df_m, x='mes_nombre', y='kwh', title="Consumo por Mes", category_orders={"mes_nombre": MESES_ORDENADOS})
            st.plotly_chart(fig_m, use_container_width=True, key="main_m")

            df_t = df_view.groupby('tarifa')['kwh'].sum().reset_index()
            fig_t = px.pie(df_t, names='tarifa', values='kwh', title="Distribución por Tarifa", hole=0.4,
                           color_discrete_map={'Alta (Punta)': '#e11d48', 'Media (Valle)': '#f59e0b', 'Baja (Super Valle)': '#10b981'})
            st.plotly_chart(fig_t, use_container_width=True, key="main_t")

        with t2:
            st.subheader("Laboratorio de Datos")
            col_x, col_y, col_tipo = st.columns(3)
            with col_x: sx = st.selectbox("Dimensión", ["hora_num", "dia_nombre", "mes_nombre", "tarifa"])
            with col_y: sy = st.selectbox("Métrica", ["kwh", "costo_total"])
            with col_tipo: stp = st.selectbox("Gráfico", ["Barras", "Líneas", "Pastel", "Área"])

            df_lab = df_view.groupby(sx)[sy].sum().reset_index()
            cat_orders = {"dia_nombre": DIAS_ORDENADOS, "mes_nombre": MESES_ORDENADOS}

            if stp == "Barras": fig_lab = px.bar(df_lab, x=sx, y=sy, color=sx, category_orders=cat_orders)
            elif stp == "Líneas": fig_lab = px.line(df_lab, x=sx, y=sy, markers=True, category_orders=cat_orders)
            elif stp == "Pastel": fig_lab = px.pie(df_lab, names=sx, values=sy)
            else: fig_lab = px.area(df_lab, x=sx, y=sy, category_orders=cat_orders)

            st.plotly_chart(fig_lab, use_container_width=True, key="lab_chart")

            if st.button("📌 Agregar esta gráfica al Informe"):
                if "pinned_charts" not in st.session_state: st.session_state.pinned_charts = []
                st.session_state.pinned_charts.append({"fig": fig_lab, "dim": sx, "met": sy})
                st.success("Gráfica anclada.")

        with t3:
            st.subheader("Generador de Prompts Profesionales (Radiografía Energética)")
            st.info("Copia el contenido del cuadro inferior y úsalo en Gemini/ChatGPT para una auditoría técnica real.")

            # --- CÁLCULOS TÉCNICOS AVANZADOS ---
            total_kwh = df_view['kwh'].sum()
            df_h_avg = df_view.groupby('hora_num')['kwh'].mean()
            h_pico = df_h_avg.idxmax()
            v_pico = df_h_avg.max()
            # Consumo base (Madrugada 00:00 - 05:00)
            c_base = df_h_avg.loc[0:5].mean()
            # Desviación (Volatilidad)
            std_kwh = df_view['kwh'].std()
            # Distribución porcentual real por tarifa
            dist_tarifa = (df_view.groupby('tarifa')['kwh'].sum() / total_kwh * 100).to_dict()

            # Prompt Estructurado
            prompt_auditoria = f"""
            Actúa como un Ingeniero Consultor en Eficiencia Energética con certificación CEM (Certified Energy Manager).
            Realiza una AUDITORÍA TÉCNICA detallada para el cliente '{cliente_sel}' basada en los siguientes DATOS REALES extraídos de su telemetría:

            1. PERFIL DE CARGA GLOBAL:
               - Consumo Total del Periodo: {total_kwh:,.2f} kWh.
               - Consumo Base (Baseload) Promedio: {c_base:,.2f} kWh (detectado en horas de madrugada).
               - Demanda Máxima Promedio: {v_pico:,.2f} kWh registrada consistentemente a las {h_pico}:00 horas.
               - Volatilidad de carga (Std Dev): {std_kwh:,.2f}.

            2. ESTRUCTURA TARIFARIA (Market Share del Consumo):
               - PUNTA (Costo más alto): {dist_tarifa.get('Alta (Punta)', 0):.2f}% del total.
               - VALLE: {dist_tarifa.get('Media (Valle)', 0):.2f}% del total.
               - SUPER VALLE: {dist_tarifa.get('Baja (Super Valle)', 0):.2f}% del total.

            3. OBJETIVOS DE LA AUDITORÍA:
               - Identificar 'Vampiros Energéticos': ¿Es el consumo base ({c_base:,.2f} kWh) demasiado alto para el giro del negocio?
               - Optimización de Picos: Sugiere 3 estrategias técnicas para mitigar el pico de las {h_pico}:00 horas.
               - Estrategia de Arbitraje: ¿Cuántos kWh se deberían desplazar de Punta a Super Valle para reducir el costo en un 15%?
               - Propuesta de Inversión: Justifica técnicamente si el perfil amerita la instalación de BESS (Sistemas de Almacenamiento por Baterías) o Paneles Solares.

            RESPUESTA REQUERIDA:
            Proporciona un análisis ejecutivo dividido en: Hallazgos, Oportunidades de Mejora y Diagnóstico Financiero. Sé extremadamente técnico y evita generalidades.
            """

            st.markdown(f'<div class="prompt-box"><b>PROMPT DE AUDITORÍA AVANZADA:</b><br><br>{prompt_auditoria}</div>', unsafe_allow_html=True)
            st.button("📋 Copiar Texto (Listo para IA)")

        with t4:
            st.subheader("Vista Previa del Informe de Gestión")
            with st.container():
                st.markdown('<div class="report-container">', unsafe_allow_html=True)
                cl, cr = st.columns([1, 2])
                with cl:
                    if logo_file: st.image(logo_file, width=150)
                with cr:
                    st.markdown(f"<h1 style='text-align:right; color:#1e40af;'>INFORME DE EFICIENCIA ENERGÉTICA</h1>", unsafe_allow_html=True)
                    st.markdown(f"<p style='text-align:right;'><b>{cliente_sel}</b> | Reporte generado el {datetime.now().strftime('%d/%m/%Y')}</p>", unsafe_allow_html=True)

                st.divider()
                st.markdown("### 1. Resumen de Operación")
                m1, m2, m3 = st.columns(3)
                m1.metric("Consumo Bruto", f"{df_view['kwh'].sum():,.2f} kWh")
                m2.metric("Costo Proyectado", f"${df_view['costo_total'].sum():,.2f}")
                m3.metric("Eficiencia (Costo/kWh)", f"${(df_view['costo_total'].sum()/df_view['kwh'].sum()):.3f}")

                st.markdown("### 2. Comportamiento Crítico (Curva Promedio)")
                st.plotly_chart(fig_h, use_container_width=True, key="report_h")

                if "pinned_charts" in st.session_state:
                    st.markdown("### 3. Profundización de Datos")
                    for i, item in enumerate(st.session_state.pinned_charts):
                        st.plotly_chart(item['fig'], use_container_width=True, key=f"pinned_{i}")

                st.markdown(f"<br><br><p><b>Consultor Responsable:</b> {nombre_consultor}<br><i>{cargo_consultor}</i></p>", unsafe_allow_html=True)
                st.markdown('</div>', unsafe_allow_html=True)

            if st.button("🗑️ Resetear Informe"):
                st.session_state.pinned_charts = []
                st.rerun()
else:
    st.info("👋 Bienvenido. Cargue el archivo de telemetría para iniciar.")