# -*- coding: utf-8 -*-
"""Aplicación de Análisis Energético Pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wkq7vgIyCTTEwjXKoUzVQbD28bj_4YDq
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import requests
import json
import base64
from io import BytesIO

# --- CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="IA Energy Consultant Pro",
    page_icon="⚡",
    layout="wide",
)

# --- ESTILOS PERSONALIZADOS ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 30px;
        border-radius: 15px;
        border-left: 8px solid #1e40af;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .stMetric {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    </style>
""", unsafe_allow_html=True)

# --- CONSTANTES Y API ---
API_KEY = ""

def llamar_ia_gemini(prompt):
    """Realiza la petición a Gemini para obtener análisis estratégico."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key={API_KEY}"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}]
    }
    try:
        response = requests.post(url, json=payload, timeout=15)
        response.raise_for_status()
        result = response.json()
        return result['candidates'][0]['content']['parts'][0]['text']
    except Exception as e:
        return "⚠️ Nota: El análisis de IA no pudo generarse automáticamente. Verifique la clave de API o la conexión."

# --- PROCESAMIENTO DE DATOS ---
@st.cache_data
def procesar_archivo(uploaded_file):
    """Carga Excel o CSV, realiza Unpivot y limpia datos con manejo robusto de NaN."""
    try:
        # Detectar tipo de archivo
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file, sep=None, engine='python')
        else:
            try:
                df = pd.read_excel(uploaded_file, sheet_name="TABLA HORARIA")
            except:
                df = pd.read_excel(uploaded_file)

        # Limpiar nombres de columnas y eliminar columnas completamente vacías
        df.columns = df.columns.str.strip()
        df = df.dropna(how='all', axis=0) # Eliminar filas vacías

        # Normalizar nombres para búsqueda
        cols_lower = [c.lower() for c in df.columns]

        if 'fecha' in cols_lower:
            # Identificar columnas de horas (asumiendo formato H1, H2... o similar)
            id_vars = [c for c in df.columns if not (c.startswith('H') and any(char.isdigit() for char in c))]
            value_vars = [c for c in df.columns if (c.startswith('H') and any(char.isdigit() for char in c))]

            if value_vars:
                # Unpivot: de formato ancho a largo
                df = df.melt(id_vars=id_vars, value_vars=value_vars, var_name='Hora_Raw', value_name='Energia')

            # Normalización post-melt
            df.columns = [c.lower() for c in df.columns]
            col_fecha = next(c for c in df.columns if 'fecha' in c)
            col_energia = next(c for c in df.columns if 'energia' in c)

            # Limpieza crítica de nulos antes de conversiones
            df = df.dropna(subset=[col_fecha, col_energia])

            df['fecha_dt'] = pd.to_datetime(df[col_fecha], errors='coerce')
            df['kWh'] = pd.to_numeric(df[col_energia], errors='coerce')
            df = df.dropna(subset=['fecha_dt', 'kWh'])

            # Manejo de Hora evitando el error de NaN a Integer
            if 'hora_raw' in df.columns:
                # Extraer números y manejar posibles nulos resultantes
                extracted_hour = df['hora_raw'].astype(str).str.extract('(\d+)')
                df['Hora_Num'] = pd.to_numeric(extracted_hour[0], errors='coerce').fillna(0).astype(int)
            else:
                df['Hora_Num'] = df['fecha_dt'].dt.hour

            df['Dia_Nombre'] = df['fecha_dt'].dt.day_name(locale='es')
            df['Mes_Nombre'] = df['fecha_dt'].dt.month_name(locale='es')

            # Asignación de Tarifas
            def categorizar_tarifa(h):
                if 13 <= h <= 18: return 'Alta (Punta)'
                elif (7 <= h <= 12) or (19 <= h <= 22): return 'Media (Valle)'
                return 'Baja (Super Valle)'

            df['Tarifa'] = df['Hora_Num'].apply(categorizar_tarifa)
            df['Costo_Total'] = df['kWh'] * 0.20

            return df
        else:
            st.error("No se encontró la columna 'fecha' en el archivo.")
            return None
    except Exception as e:
        st.error(f"Error procesando el archivo: {e}")
        return None

# --- MÓDULO DE AUTENTICACIÓN ---
def gestionar_login():
    if "auth_state" not in st.session_state:
        st.session_state.auth_state = False

    if not st.session_state.auth_state:
        st.title("🔐 Acceso Plataforma Energy BI")
        col1, _ = st.columns([1, 1])
        with col1:
            u = st.text_input("Usuario")
            p = st.text_input("Contraseña", type="password")
            if st.button("Ingresar"):
                usuarios = {"admin": "admin123", "cliente": "cliente2025"}
                if u in usuarios and usuarios[u] == p:
                    st.session_state.auth_state = True
                    st.session_state.user_role = "Administrador" if u == "admin" else "Cliente"
                    st.session_state.user_name = u
                    st.rerun()
                else:
                    st.error("Credenciales incorrectas")
        return False
    return True

# --- INTERFAZ PRINCIPAL ---
if gestionar_login():
    st.sidebar.title(f"Hola, {st.session_state.user_name}")
    if st.sidebar.button("Cerrar Sesión"):
        st.session_state.auth_state = False
        st.rerun()

    if st.session_state.user_role == "Administrador":
        uploaded_file = st.sidebar.file_uploader("Cargar Datos (CSV o XLSX)", type=["csv", "xlsx"])
        if uploaded_file:
            data = procesar_archivo(uploaded_file)
            if data is not None:
                st.session_state.df_master = data
                st.sidebar.success("✅ Datos cargados correctamente")

    if "df_master" in st.session_state:
        df = st.session_state.df_master

        # Filtros de cliente/sede
        col_nombre = 'nombre' if 'nombre' in df.columns else None
        nombres = ["Todos"] + sorted(list(df[col_nombre].unique())) if col_nombre else ["Todos"]
        cliente_sel = st.sidebar.selectbox("Seleccionar Cliente", nombres)
        df_view = df if cliente_sel == "Todos" else df[df[col_nombre] == cliente_sel]

        # Pestañas
        t1, t2, t3, t4 = st.tabs(["📊 Análisis", "🧪 Laboratorio", "💡 IA & Ahorro", "📄 Informe"])

        with t1:
            st.subheader(f"Análisis Energético: {cliente_sel}")
            c1, c2 = st.columns(2)
            df_h = df_view.groupby('Hora_Num')['kWh'].mean().reset_index()
            c1.plotly_chart(px.line(df_h, x='Hora_Num', y='kWh', title="Curva de Carga Promedio (Promedio kWh/Hora)"), use_container_width=True)
            df_d = df_view.groupby('Dia_Nombre')['kWh'].sum().reset_index()
            c2.plotly_chart(px.bar(df_d, x='Dia_Nombre', y='kWh', title="Consumo Total por Día de la Semana"), use_container_width=True)

        with t2:
            st.subheader("Gráficas Personalizadas")
            ca, cb, cc = st.columns(3)
            with ca: gx = st.selectbox("Eje X", ["Hora_Num", "Dia_Nombre", "Tarifa", "Mes_Nombre"])
            with cb: gy = st.selectbox("Eje Y", ["kWh", "Costo_Total"])
            with cc: gt = st.radio("Tipo de Visualización", ["Barras", "Líneas"])

            plot_data = df_view.groupby(gx)[gy].sum().reset_index()
            fig_custom = px.bar(plot_data, x=gx, y=gy) if gt == "Barras" else px.line(plot_data, x=gx, y=gy)
            st.plotly_chart(fig_custom, use_container_width=True)

        with t3:
            st.subheader("Escenarios de Optimización con IA")
            p_mover = st.slider("% Energía a desplazar de franja Punta", 0, 100, 20)
            e_punta = df_view[df_view['Tarifa'] == 'Alta (Punta)']['kWh'].sum()
            ahorro_est = e_punta * (p_mover/100) * 0.10

            st.metric("Ahorro Estimado Proyectado", f"${ahorro_est:,.2f}")

            if st.button("🤖 Generar Análisis IA"):
                with st.spinner("Procesando patrones de consumo..."):
                    contexto = f"Cliente: {cliente_sel}. Consumo total: {df_view['kWh'].sum():,.2f} kWh. Ahorro potencial: ${ahorro_est:,.2f}."
                    st.session_state.ia_result = llamar_ia_gemini(f"Analiza este escenario energético y da 3 consejos: {contexto}")
                    st.write(st.session_state.ia_result)

        with t4:
            st.subheader("Informe Ejecutivo")
            st.markdown(f"""
            <div class="report-container">
                <h2 style='color:#1e40af'>REPORTE ENERGÉTICO PROFESIONAL</h2>
                <p><b>Cliente Analizado:</b> {cliente_sel}</p>
                <p><b>Consumo Total del Periodo:</b> {df_view['kWh'].sum():,.2f} kWh</p>
                <p><b>Ahorro Potencial Identificado:</b> ${ahorro_est:,.2f}</p>
                <hr>
                <h4>Conclusiones Estratégicas:</h4>
                <p>{st.session_state.get('ia_result', 'Análisis de IA pendiente de generación.')}</p>
            </div>
            """, unsafe_allow_html=True)
            st.caption("Nota: Para descargar, presione Ctrl+P y elija 'Guardar como PDF'.")
    else:
        st.info("👋 El sistema está listo. Por favor, cargue un archivo CSV o Excel desde el panel lateral.")